function writeElectrodes(electrodes, path)
    extn = '';
    posListFileName = [path '/positionList_ISI',extn,'.txt'];
    fid = fopen(posListFileName, 'w');
    if fid == -1
        error('Author:Function:OpenFile', 'Cannot open file: %s', posListFileName);
    end

    hdrLine = 'Number   Name   ml1   ap1   dv1   ml2   ap2   dv2   use  mlDist apDist electrodeNr \n';
    fprintf(fid,hdrLine);

    % switch from (- = right) to (- = left) convention
    bl = ' ';
    for tr=1:length(electrodes)
        cur_line = [                                                                    ...
                    int2str(tr)                                                      bl   ...
                    electrodes(tr).name                                              bl   ...
                    num2str(-0.1*electrodes(tr).pos(2))                              bl   ...
                    num2str( 0.1*electrodes(tr).pos(1))                              bl   ...
                    num2str( 0.1*electrodes(tr).pos(3))                              bl   ...
                    num2str(-0.1*(electrodes(tr).pos(2)+electrodes(tr).normal(2)))   bl   ...
                    num2str( 0.1*(electrodes(tr).pos(1)+electrodes(tr).normal(1)))   bl   ...
                    num2str( 0.1*(electrodes(tr).pos(3)+electrodes(tr).normal(3)))   bl   ...
                    int2str(1)                                                       bl   ...
                    num2str( 0.1*electrodes(tr).mlDist)                              bl   ...
                    num2str( 0.1*electrodes(tr).apDist)                              bl   ...
                    int2str(tr)                                                    '\n'];

%         if(electrodes(tr).use == 1)        
%              fprintf(fid, cur_line); 
%         end
        fprintf(fid, cur_line);

    end % loop trials
    fclose(fid);
    
    posListFileName = [path '/positionListSkull_ISI',extn,'.txt'];
    fid = fopen(posListFileName, 'w');

    hdrLine = 'Number   Name   ml1   ap1   dv1   ml2   ap2   dv2   use   electrodeNr  \n';
    fprintf(fid,hdrLine);

    % switch from (- = right) to (- = left) convention
    bl = ' ';
    for tr=1:length(electrodes)
        cur_line = [                                                                             ...
                    int2str(tr)                                                             bl   ...
                    electrodes(tr).name                                                     bl   ...
                    num2str(-0.1*electrodes(tr).skull(2))                                   bl   ...
                    num2str( 0.1*electrodes(tr).skull(1))                                   bl   ...
                    num2str( 0.1*electrodes(tr).skull(3))                                   bl   ...
                    num2str(-0.1*(electrodes(tr).skull(2)+electrodes(tr).normalSkull(2)))   bl   ...
                    num2str( 0.1*(electrodes(tr).skull(1)+electrodes(tr).normalSkull(1)))   bl   ...
                    num2str( 0.1*(electrodes(tr).skull(3)+electrodes(tr).normalSkull(3)))   bl   ...
                    int2str(1)                                                              bl   ...
                    int2str(tr)                                                    '      \n'];

%         if(electrodes(tr).use == 1)        
%             fprintf(fid, cur_line); 
%         end
        fprintf(fid, cur_line); 

    end % loop trials
    fclose(fid);
    
end